# This is a basic workflow to help you get started with Actions

name: Generate and deploy docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-docs:
    name: Update readme
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/github-pages-deploy-action@master
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LANGUAGE: "java"
          MAKE_COMMAND: "make html"
          PAGES_BRANCH: "gh-pages"
          BUILD_FROM: "develop"
          DOCS_FOLDER: "output"
